
ig.baked=true;ig.module('game.entities.goal').requires('impact.entity','impact.entity-pool').defines(function(){EntityGoal=ig.Entity.extend({size:{x:96,y:128},maxVel:{x:0,y:0},offset:{x:76,y:0},type:ig.Entity.TYPE.NONE,checkAgainst:ig.Entity.TYPE.A,collides:ig.Entity.COLLIDES.NONE,spawnBalloon:false,triggered:false,pauseFrame:0,animSheet:new ig.AnimationSheet('media/chocolate-fountain.png',64,128),zIndex:-1,init:function(x,y,settings){this.parent(x,y,settings);this.spawnBalloonTimer=new ig.Timer(0);this.addAnim('idle',0.1,[0,1,2,3,4,5,6,7,8]);},reset:function(x,y,settings){this.parent(x,y,settings);this.spawnBalloon=false;this.triggered=false;if(!ig.global.wm){ig.game.setBonusValues();}},paused:function(){if(this.currentAnim){this.pauseFrame=this.currentAnim.frame;}},unpaused:function(){this.currentAnim.gotoFrame(this.pauseFrame);},update:function(){if(ig.game.pause&&!this.pause||this.waitingBro){this.paused();}
else if(this.pause&&!ig.game.pause){this.unpaused();}
if(this.pause&&this.currentAnim){this.currentAnim.gotoFrame(this.pauseFrame);}
else{this.currentAnim=this.anims.idle;}
if(this.spawnBalloon&&this.spawnBalloonTimer.delta()>0){this.spawnBalloon=false;ig.game.spawnEntity(EntityBalloons,this.pos.x-this.offset.x+4,this.pos.y+(this.size.y/2),{left:true});ig.game.spawnEntity(EntityBalloons,this.pos.x-this.offset.x+14,this.pos.y+(this.size.y/2),{left:false});if((ig.game.pData.tokensLT+ig.game.bonusNum)>=ig.game.currentHighScore&&ig.game.hasHighScore){console.log("NEW HIGH SCORE! ");var sPosX=this.pos.x-40;var sPosY=this.pos.y+30;ig.game.spawnEntity(EntityScore,sPosX,sPosY,{value:"newHighScore"});if(!ig.game.muteGame){ig.game.newHighScore.volume=.15;ig.game.newHighScore.play();}}}
this.parent();},check:function(other){if(other instanceof EntityPlayer&&!other.dying){if(ig.game.pData.lvl==ig.game.totalLevels){ig.game.gameWon=true;}
var player=ig.game.getEntityByName('player');if(player.victoryDance!=true&&!this.triggered){this.triggered=true;ig.game.bonusNum=0;ig.game.bonus=0;ig.game.showBonus=true;if(ig.game.bonusTimer.delta()<0){ig.game.bonus=ig.game.round5(Math.round(ig.game.bonusValue*ig.game.bonusTimer.delta()));}
ig.game.bonusNum=ig.game.bonus;ig.game.processTokens("bank");player.anims.win.rewind();player.victoryDance=true;this.spawnBalloonTimer.set(.95);this.spawnBalloon=true;player.victoryTimer.set(2.75);ig.music.stop();ig.game.bonusTimer.pause();ig.game.wonTheLevel=true;if(!ig.game.muteGame){ig.game.victorySound.volume=.2;ig.game.victorySound.play();}}}}});ig.EntityPool.enableFor(EntityGoal);});

