
ig.baked=true;ig.module('game.entities.wizard').requires('impact.entity','impact.entity-pool').defines(function(){EntityWizard=ig.Entity.extend({size:{x:25,y:20},offset:{x:30,y:13},maxVel:{x:500,y:1000},storeMaxVel:{x:500,y:1000},storeVel:{x:null,y:null},friction:{x:400,y:0},zIndex:99,type:ig.Entity.TYPE.B,checkAgainst:ig.Entity.TYPE.A,collides:ig.Entity.COLLIDES.PASSIVE,health:1,speed:0,flip:false,idle:false,pause:false,kOTB:false,waitingBro:true,synced:false,delay:1,name:"wizard",air:null,tNum:null,sleeping:true,waking:false,wizard:true,disappearing:false,vanishTime:.5,disappearTime:.7,_wmDrawBox:true,_wmBoxColor:'rgba(253, 73, 63, 1)',appearSound:new ig.Sound('media/sounds/wiz-appear.*'),deadSound:new ig.Sound('media/sounds/wiz-dead.*'),animSheets:{gwAppear:new ig.AnimationSheet('media/wizard-appear-ground.png',56,56),awAppear:new ig.AnimationSheet('media/wizard-appear-air.png',56,56),gwCast:new ig.AnimationSheet('media/wizard-attack-ground.png',56,56),awCast:new ig.AnimationSheet('media/wizard-attack-air.png',56,56),},init:function(x,y,settings){this.parent(x,y,settings);var randomJumpTime=1+Math.floor(Math.random()*3);this.idleTimer=new ig.Timer(0);this.disappearTimer=new ig.Timer(0);this.vanishTimer=new ig.Timer(0);this.runTimer=new ig.Timer(0);this.attackTimer=new ig.Timer(0);this.dieUpTimer=new ig.Timer(0);this.delayTimer=new ig.Timer(0);this.wakeTimer=new ig.Timer(0);this.shootingTimer=new ig.Timer(0);this.anims.gwAppear=new ig.Animation(this.animSheets.gwAppear,.05,[0,1,2,3,4,5,6,7,8,9,10,11]);this.anims.awAppear=new ig.Animation(this.animSheets.awAppear,.05,[0,1,2,3,4,5,6,7,8,9,10,11]);this.anims.gwDisappear=new ig.Animation(this.animSheets.gwAppear,.05,[9,8,7,6,5,4,3,2,1,0],true);this.anims.awDisappear=new ig.Animation(this.animSheets.awAppear,.05,[9,8,7,6,5,4,3,2,1,0],true);this.anims.gwIdle=new ig.Animation(this.animSheets.gwAppear,.05,[10,11]);this.anims.awIdle=new ig.Animation(this.animSheets.awAppear,.05,[10,11]);this.anims.gwShoot=new ig.Animation(this.animSheets.gwCast,.05,[0,1,2,3,4,5,6,7,7,7,7,7,7,8]);this.anims.awShoot=new ig.Animation(this.animSheets.awCast,.05,[0,1,2,3,4,5,6,7,7,7,7,7,7,8]);if(!ig.global.wm){this.configure();}},reset:function(x,y,settings){this.parent(x,y,settings);this.configure();},facePlayer:function(){var player=ig.game.getEntityByName('player');this.flip=player.pos.x+player.size.x>this.pos.x?true:false;},configure:function(){if(this.air){this.name="airWizard";}
else{this.name="groundWizard";}
this.kOTB=false;this.waitingBro=true;this.synced=false;this.sleeping=true;this.shooting=false;this.waking=false;this.disappearing=false;},wakeup:function(){this.sleeping=false;this.waking=true;this.wakeTimer.set(.6);this.anims.awAppear.rewind();this.anims.gwAppear.rewind();this.facePlayer();if(!ig.game.muteGame){this.appearSound.volume=.12;this.appearSound.play();}
var disappearTime=this.air?2:4;},checkCond:function(){if(this.shooting&&this.shootingTimer.delta()>0){this.shootingTimer.set(.7);var arPosX=this.flip?this.pos.x+32:this.pos.x+6;var arPosY=this.pos.y-4;if(this.air){ig.game.spawnEntity(EntitySpell,arPosX,arPosY,{flip:this.flip,air:true});}
else{ig.game.spawnEntity(EntitySpell,arPosX,arPosY,{flip:this.flip});}}
if(this.waking&&this.wakeTimer.delta()>0){this.waking=false;this.shooting=true;this.shootingTimer.set(.35);this.disappearTimer.set(this.disappearTime);this.anims.gwShoot.rewind();this.anims.awShoot.rewind();}
if(this.shooting&&this.disappearTimer.delta()>0){this.shooting=false;this.disappearing=true;this.vanishTimer.set(this.vanishTime);this.anims.gwDisappear.rewind();this.anims.awDisappear.rewind();}
if(this.disappearing&&this.vanishTimer.delta()>0&&!this.kOTB){this.kill();}},pauseTimers:function(){this.shootingTimer.pause();this.runTimer.pause();this.idleTimer.pause();this.vanishTimer.pause();this.disappearTimer.pause();this.attackTimer.pause();this.dieUpTimer.pause();this.wakeTimer.pause();},unpauseTimers:function(){this.wakeTimer.unpause();this.shootingTimer.unpause();this.vanishTimer.unpause();this.runTimer.unpause();this.idleTimer.unpause();this.disappearTimer.unpause();this.attackTimer.unpause();this.dieUpTimer.unpause();},paused:function(){if(!this.storeVel.x){this.storeVel.x=this.vel.x;}
if(!this.storeVel.y){this.storeVel.y=this.vel.y;}
this.vel.x=0;this.vel.y=0;this.maxVel.x=0;this.maxVel.y=0;this.storedSpeed=this.speed;this.speed=0;if(this.currentAnim){this.pauseFrame=this.currentAnim.frame;}
this.pauseTimers();this.pause=true;},unpaused:function(){this.maxVel.x=this.storeMaxVel.x;this.maxVel.y=this.storeMaxVel.y;this.vel.x=this.storeVel.x;this.vel.y=this.storeVel.y;this.storeVel.x=null;this.storeVel.y=null;this.speed=this.storedSpeed;if(this.currentAnim){this.currentAnim.gotoFrame(this.pauseFrame);}
this.unpauseTimers();this.pause=false;},update:function(){if(!this.synced&&this.waitingBro&&ig.game.syncNow){this.synced=true;this.delayTimer.set(this.delay);}
else if(this.waitingBro&&ig.game.syncNow&&this.delayTimer.delta()>0){this.waitingBro=false;}
if(ig.game.pause&&!this.pause||this.waitingBro){this.paused();}
else if(this.pause&&!ig.game.pause){this.unpaused();}
if(!this.pause){this.checkCond();this.offSets();this.movements();}
this.animateMe();if(this.kOTB){this.boundaries();}
this.parent();},offSets:function(){this.offset.x=this.flip?2:30;this.offset.y=22;},movements:function(){if(this.kOTB){if(ig.game.getEntityByName('player')){var player=ig.game.getEntityByName('player');if(player.pos.x>this.pos.x){this.vel.x=-220;}
else{this.vel.x=220;}}
if(this.dieUpTimer.delta()<0){var bFF=this.dieUpTimer.delta()*-1;this.vel.y=-2000*bFF;}
else{var bFF=this.dieUpTimer.delta();if(bFF>1){bFF=1;}
this.vel.y=1000*bFF;}}
else{if(this.air){if(!this.sleeping){this.pos.x=this.flip?Math.round(ig.game.screen.x+ig.system.width*.1):Math.round(ig.game.screen.x+ig.system.width*.85);this.pos.y=ig.game.screen.y+ig.system.height*.35}
else{this.vel.x=0;this.vel.y=0;this.maxVel.y=0;}}
else{var xdir=this.flip?-1:1;this.vel.x=0;this.vel.y=0;}}},kill:function(){this.parent();},animateMe:function(){if(this.pause&&this.currentAnim){this.currentAnim.gotoFrame(this.pauseFrame);}
else if(this.waking){this.currentAnim=this.air?this.anims.awAppear:this.anims.gwAppear;}
else if(this.sleeping){this.currentAnim=null;}
else if(this.disappearing){this.currentAnim=this.air?this.anims.awDisappear:this.anims.gwDisappear;}
else if(this.shooting){this.currentAnim=this.air?this.anims.awShoot:this.anims.gwShoot;}
else{this.currentAnim=this.air?this.anims.awIdle:this.anims.gwIdle;}
if(this.currentAnim){this.currentAnim.flip.x=this.flip;}
if(this.kOTB&&!this.pause){if(this.currentAnim){this.currentAnim=this.air?this.anims.awIdle:this.anims.gwIdle;this.currentAnim.angle-=Math.PI/.25*ig.system.tick;}}
else{if(this.currentAnim){this.currentAnim.angle=0;}}},handleMovementTrace:function(res){if(this.kOTB||this.air){this.pos.x+=this.vel.x*ig.system.tick;this.pos.y+=this.vel.y*ig.system.tick;}
else{this.parent(res);}},knockMeOutTheBox:function(){this.kOTB=true;this.dieUpTimer.set(.35);if(ig.game.getEntityByName('player')){var player=ig.game.getEntityByName('player')
if(!ig.game.muteGame){this.deadSound.volume=.075;this.deadSound.play();}}
if(!ig.game.muteGame){this.deadSound.volume=.2;this.deadSound.play();}
var myValue=ig.game.rainbowKillCounter(this.name);var sPosX=this.pos.x-15;var sPosY=this.pos.y-(this.size.y/2)-22-(ig.game.rainbowKillCount*10);if(!ig.game.playerDead&&!ig.game.dying){ig.game.spawnEntity(EntityScore,sPosX,sPosY,{value:myValue});}},boundaries:function(){if(this.pos.y>ig.system.height*1.5+ig.game.screen.y){this.kill();}},check:function(other){if(ig.game.getEntityByName('player')&&this.shooting){var player=ig.game.getEntityByName('player')
if(player.attacking&&!this.kOTB){this.knockMeOutTheBox();}
else if(!ig.game.quiz&&this.attackTimer.delta()>0&&!this.kOTB&&!player.attacking){ig.game.quizbox.quiz(1,this.name);this.attackTimer.set(ig.game.enemyRecoveryTime);}
if(!this.kOTB){this.knockMeOutTheBox();}}}});EntitySpell=ig.Entity.extend({size:{x:6,y:6},offset:{x:3,y:3},maxVel:{x:1000,y:0},storeMaxVel:{x:1000,y:0},storeVel:{x:null,y:null},friction:{x:0,y:0},gravityFactor:0,xPath:null,yPath:null,velWalled:false,type:ig.Entity.TYPE.B,checkAgainst:ig.Entity.TYPE.A,collides:ig.Entity.COLLIDES.NEVER,zIndex:120,health:1,gravity:0,pause:false,kOTB:false,bounceDir:null,speed:235,storedSpeed:null,flip:false,name:"spell",boom:false,attackSound:new ig.Sound('media/sounds/wiz-shot.*'),hitSound:new ig.Sound('media/sounds/wiz-hit.*'),fizzleSound:new ig.Sound('media/sounds/wiz-fizzle.*'),animSheet:new ig.AnimationSheet('media/wiz-star.png',12,12),init:function(x,y,settings){this.parent(x,y,settings);this.addAnim('fly',0.05,[0,1,2]);this.configureMe();},reset:function(x,y,settings){this.parent(x,y,settings);this.configureMe();},knockMeOutTheBox:function(){this.kOTB=true;},configureMe:function(){this.kOTB=false;this.boom=false;ig.game.sortEntitiesDeferred();if(this.air){var player=ig.game.getEntityByName('player')
var angle=this.angleTo(player);var addThis=this.flip?130:100;this.vel.x=(Math.cos(angle)*this.speed)+addThis;this.vel.y=Math.sin(angle)*this.speed;this.maxVel.y=1000;}
if(!ig.game.muteGame){this.attackSound.volume=.15;this.attackSound.play();}},paused:function(){if(!this.storeVel.x){this.storeVel.x=this.vel.x;}
if(!this.storeVel.y){this.storeVel.y=this.vel.y;}
this.vel.x=0;this.vel.y=0;this.maxVel.x=0;this.maxVel.y=0;this.storedSpeed=this.speed;this.speed=0;if(this.currentAnim){this.pauseFrame=this.currentAnim.frame;}
this.pause=true;},unpaused:function(){this.maxVel.x=this.storeMaxVel.x;this.maxVel.y=this.storeMaxVel.y;this.vel.x=this.storeVel.x;this.vel.y=this.storeVel.y;this.storeVel.x=null;this.storeVel.y=null;this.speed=this.storedSpeed;this.currentAnim.gotoFrame(this.pauseFrame);this.pause=false;},update:function(){if(ig.game.pause&&!this.pause||ig.game.getEntityByName('player')&&ig.game.getEntityByName('player').landed!=true){this.paused();}
else if(this.pause&&!ig.game.pause){this.unpaused();}
this.checkConditions();if(!this.pause){this.movements();if(this.boom){this.spawnSparkle();}}
this.animateMe();this.parent();},spawnSparkle:function(){var spkPosX=this.pos.x;var spkPosY=this.pos.y;ig.game.spawnEntity(EntitySparkle,spkPosX,spkPosY,{flip:this.flip,wizard:true});this.kill();},killMe:function(){this.boom=true;},checkConditions:function(){if(ig.game.getEntityByName('player')){var player=ig.game.getEntityByName('player');if(player.victoryDance){this.spawnSparkle();}}},movements:function(){if(!this.air){var xSpeed=this.flip?this.speed:-this.speed;this.vel.x=xSpeed;this.vel.y=0;}},animateMe:function(){if(this.pause&&this.currentAnim){this.currentAnim.gotoFrame(this.pauseFrame);}
else{this.currentAnim=this.anims.fly;}
if(this.currentAnim){this.currentAnim.flip.x=this.flip;}},receiveDamage:function(amount,from){this.health-=amount;if(this.health<=0){this.killMe();}},handleMovementTrace:function(res){this.parent(res);if(res.collision.y||res.collision.slope||res.collision.x){this.killMe();}},check:function(other){if(ig.game.getEntityByName('player')){if(!ig.game.muteGame){}
var player=ig.game.getEntityByName('player');if(other==player&&!player.invin&&!player.attacking){if(!ig.game.quiz){ig.game.quizbox.quiz(1,this.name);if(!ig.game.muteGame){this.hitSound.volume=.15;this.hitSound.play();}
this.killMe();}}
else if(other==player&&!this.kOTB&&player.invin||other==player&&player.attacking){if(!ig.game.muteGame){this.fizzleSound.volume=.2;this.fizzleSound.play();}
this.killMe();}}}});ig.EntityPool.enableFor(EntityWizard);ig.EntityPool.enableFor(EntitySpell);});

