
ig.baked=true;ig.module('game.entities.wiztrigger').requires('impact.entity','impact.entity-pool').defines(function(){EntityWiztrigger=ig.Entity.extend({size:{x:32,y:32},offset:{x:-2,y:-2},maxVel:{x:0,y:0},_wmDrawBox:true,_wmBoxColor:'rgba(253, 73, 63, .2)',_wmScalable:true,zIndex:-10,bounciness:0,landed:false,type:ig.Entity.TYPE.B,checkAgainst:ig.Entity.TYPE.BOTH,collides:ig.Entity.COLLIDES.NEVER,health:3000,name:"wiztrigger",active:false,pause:false,spawnCollisionTiles:function(){var xTiles=0;var xPos=0;var yTiles=0;while(xTiles<4){ig.game.collisionMap.setTile(this.pos.x+xPos,this.pos.y,1);ig.game.collisionMap.setTile(this.pos.x+xPos,this.pos.y+8,1);ig.game.collisionMap.setTile(this.pos.x+xPos,this.pos.y+16,1);ig.game.collisionMap.setTile(this.pos.x+xPos,this.pos.y+24,1);ig.game.collisionMap.setTile(this.pos.x+xPos,this.pos.y+31,1);xPos+=8;xTiles++;}
this.size.y+=2;this.pos.y-=1;this.offset.y=-2;},removeCollisionTiles:function(){var xTiles=0;var xPos=0;var yTiles=0;this.size.y-=2;this.pos.y+=1;while(xTiles<4){ig.game.collisionMap.setTile(this.pos.x+xPos,this.pos.y,0);ig.game.collisionMap.setTile(this.pos.x+xPos,this.pos.y+8,0);ig.game.collisionMap.setTile(this.pos.x+xPos,this.pos.y+16,0);ig.game.collisionMap.setTile(this.pos.x+xPos,this.pos.y+24,0);ig.game.collisionMap.setTile(this.pos.x+xPos,this.pos.y+31,0);xPos+=8;xTiles++;}},pauseTimers:function(){this.dieTimer.pause();},unpauseTimers:function(){this.dieTimer.unpause();},paused:function(){this.pauseTimers();this.pause=true;},unpaused:function(){this.unpauseTimers();this.pause=false;},init:function(x,y,settings){this.parent(x,y,settings);this.dieTimer=new ig.Timer(0);if(!ig.global.wm){this.active=false;}},reset:function(x,y,settings){if(!ig.global.wm){ig.game.sortEntitiesDeferred();}
this.active=false;this.parent(x,y,settings);},update:function(){if(ig.game.pause&&!this.pause){this.paused();}
else if(this.pause&&!ig.game.pause){this.unpaused();}
if(this.pause==false&&ig.game.quiz==true||this.pause==false&&ig.game.cutScene==true){this.pause=true;this.paused();}
if(this.pause==true&&ig.game.quiz==false&&ig.game.cutScene==false){this.pause=false;this.unpaused();}
if(this.active&&this.dieTimer.delta()>0){this.kill();}
this.parent();},check:function(other){if(this.active&&other.sleeping&&other.wizard){other.wakeup();}
if(ig.game.getEntityByName('player')){var player=ig.game.getEntityByName('player');if(other==player&&!this.active){if(!ig.game.muteGame){}
this.active=true;this.dieTimer.set(1);}}}});ig.EntityPool.enableFor(EntityWiztrigger);});

